### ISSUE TITLE
Basic Required Functionality checklist

### ISSUE THREAD

**Issue by NoRaincheck** [chappers/Dave#2]
Python
- [x] Factset
- [x] Feature Snapshotting
- [ ] Import from ~~Ivory~~ formats supported by `Pandas`
- [ ] Export to ~~Ivory~~ various formats, such as `tsv`, `psv`, `csv`, `feather`

R
- [x] Factset
- [x] Feature Snapshotting
- [ ] Import from ~~Ivory~~ formats supported by `readr`
- [ ] Export to ~~Ivory~~ various formats, such as `tsv`, `psv`, `csv`, `feather`
